tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "isen-ng/dotnet-sdk-versions"
tap "jakehilborn/jakehilborn"
tap "samuelmeuli/tap"
brew "python@3.9"
brew "awscli"
brew "dnsmasq"
brew "docker", link: false
brew "docker-compose", link: false
brew "unbound"
brew "gnutls"
brew "fzf"
brew "git"
brew "git-flow"
brew "grip"
brew "httpie"
brew "jq"
brew "libpng"
brew "libssh2"
brew "libyaml"
brew "mas"
brew "mitmproxy"
brew "neovim"
brew "nginx"
brew "node"
brew "node-build"
brew "nodenv"
brew "p7zip"
brew "python@2", link: false
brew "redis"
brew "ripgrep"
brew "ruby"
brew "ruby-build"
brew "tmux"
brew "vim"
brew "watch"
cask "docker"
cask "font-hack-nerd-font"
cask "ngrok"
cask "react-native-debugger"
cask "rectangle"
mas "GarageBand", id: 682658836
mas "Microsoft Remote Desktop", id: 1295203466
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
