format = """
$os\
$directory\
$git_branch\
$git_status\
$git_metrics\
$all\
$docker_context\
$lua\
$gradle\
$java\
$ruby\
$dotnet\
$nodejs\
$character"""

[directory]
style = 'fg:#e0c989'
truncation_symbol = '.../'

[docker_context]
format = '$symbol '

[git_branch]
format = ' [$symbol$branch]($style) '
style = 'fg:#719cd6'

[git_metrics]
disabled = false
added_style = 'fg:#e0c989'
deleted_style = 'fg:#e0c989'

[git_status]
ahead = '⇡$count'
behind = '⇣$count'
style = 'fg:#e0c989'

[gradle]
format = '$symbol '

[java]
disabled = false
format = '[$symbol$version]($style) '
style = 'fg:#719cd6'

[lua]
disabled = false
format = '$symbol '

[nodejs]
format = '[$symbol$version]($style) '
style = 'fg:#719cd6'

[os]
disabled = false
style = 'fg:#719cd6'

[os.symbols]
Macos = ' '

[ruby]
disabled = false
format = '[$symbol$version]($style) '
style = 'fg:#719cd6'
