format = """
$os\
$directory\
$git_branch\
$git_status\
$git_metrics\
$all\
$nodejs\
$character"""

[directory]
style = 'fg:#e0c989'
truncation_length = 5
truncation_symbol = '.../'

[docker_context]
format = '$symbol '

[dotnet]
disabled = true

[git_branch]
format = ' [$symbol$branch]($style) '
style = 'fg:#719cd6'

[git_metrics]
disabled = false
added_style = 'fg:#e0c989'
deleted_style = 'fg:#e0c989'

[git_status]
style = 'fg:#e0c989'

[java]
disabled = true

[lua]
disabled = true

[nodejs]
format = ' [$symbol$version]($style) '
style = 'fg:#719cd6'

[os]
disabled = true
style = 'fg:#719cd6'

[os.symbols]
Macos = '  '

[ruby]
disabled = true
