format = """
[┌───](bold #9d79d6) \
$os\
$cmd_duration\
$directory\
$git_branch\
$git_status\
$git_metrics
[└──](bold #9d79d6) \
$docker_context\
$lua\
$gradle\
$java\
$ruby\
$swift\
$rust\
$dotnet\
$nodejs\
$character"""

add_newline = false

[cmd_duration]
format = '[$duration]($style) '
min_time = 1
style = 'fg:#719cd6'

[directory]
style = 'fg:#e0c989'
truncation_length = 2
truncation_symbol = '.../'
truncate_to_repo = false

[docker_context]
format = '$symbol '

[git_branch]
format = ' [$symbol$branch]($style) '
style = 'fg:#9d79d6'

[git_metrics]
disabled = false
added_style = 'fg:#9d79d6'
deleted_style = 'fg:#9d79d6'

[git_status]
ahead = '⇡$count'
behind = '⇣$count'
diverged = '⇕$behind_count⇣$ahead_count⇡'
style = 'fg:#9d79d6'

[gradle]
format = '[$symbol($version)]($style) '

[java]
disabled = false
format = '[$symbol$version]($style) '
style = 'fg:#719cd6'

[lua]
disabled = false
format = '[$symbol($version)]($style) '

[nodejs]
format = '$symbol[$version]($style) '
style = 'fg:#719cd6'

[os]
disabled = false
style = 'fg:#719cd6'

[os.symbols]
Macos = ' '

[package]
disabled = true

[ruby]
disabled = false
format = '[$symbol$version]($style) '
style = 'fg:#719cd6'

[swift]
format = '[$symbol$version]($style) '
style = 'fg:#719cd6'
