add_newline = true

format = """
[┌───](bold purple) \
${os}\
${cmd_duration}\
${directory}
[│](bold purple)   ${git_branch}\
${git_status}\
${git_metrics}\
${git_commit}
[└──](bold purple) \
${docker_context}\
${lua}\
${gradle}\
${java}\
${ruby}\
${swift}\
${rust}\
${dotnet}\
${nodejs}\
${jobs}\
${character}"""

palette = 'nightfox'
[palettes.nightfox]
blue = '#719CD6'
cyan = '#7AD5D6'
green = '#81B29A'
orange = '#F4A261'
purple = '#9D79D6'
red = '#C94F6D'
white = '#AEAFB0'
yellow = '#E0C989'

[cmd_duration]
format = '[${duration}](${style}) '
min_time = 1
style = 'fg:blue'

[directory]
style = 'fg:yellow'
truncation_length = 5
truncation_symbol = '.../'
truncate_to_repo = false

[docker_context]
format = '${symbol} '

[git_branch]
format = ' [${symbol}${branch}](${style}) '
style = 'fg:purple'

[git_commit]
style = 'green'

[git_metrics]
disabled = false
added_style = 'fg:purple'
deleted_style = 'fg:purple'

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕${behind_count}⇣${ahead_count}⇡'
style = 'fg:purple'

[gradle]
format = '[${symbol}(${version})](${style}) '

[java]
disabled = false
format = '[${symbol}${version}](${style}) '

[jobs]
format = '[${symbol}${number}](${style}) '
number_threshold = 1
style = 'fg:orange'
symbol_threshold = 1

[lua]
disabled = false
format = '[${symbol}(${version})](${style}) '

[nodejs]
format = '${symbol}[${version}](${style}) '

[os]
disabled = false
style = 'fg:blue'

[os.symbols]
Macos = ' '

[package]
disabled = true

[ruby]
disabled = false
format = '[${symbol}${version}](${style}) '
