nmap('<leader>tb', '<cmd>lua require("telescope.builtin").buffers()<CR>', { desc = 'buffers' })
nmap('<leader>td', '<cmd>lua require("telescope.builtin").diagnostics()<CR>', { desc = 'diagnostics' })
nmap('<leader>tf', '<cmd>lua require("telescope.builtin").find_files()<CR>', { desc = 'find files' })
nmap('<leader>tg', '<cmd>lua require("modules.telescope.git").git_status()<CR>', { desc = 'git status' })
nmap('<leader>ti', '<cmd>:Telescope import<CR>', { desc = 'js import' })
nmap('<leader>tm', '<cmd>:Telescope notify<CR>', { desc = 'messages', })
nmap('<leader>tn', '<cmd>:Telescope node_modules list<CR>', { desc = 'node modules' })
nmap('<leader>tp', '<cmd>lua require("modules.telescope.nightfox").get_palette()<CR>', { desc = 'nightfox palette' })
nmap('<leader>tr', '<cmd>lua require("telescope.builtin").live_grep()<CR>', { desc  = 'ripgrep'})
nmap('<leader>ts', '<cmd>lua require("modules.telescope.git").git_status_staged()<CR>', { desc = 'git status' })
nmap('<leader>tu', '<cmd>:Telescope undo<CR>', { desc  = 'undo'})
nmap('<leader>.', '<cmd>:Telescope file_browser path=%:p:h select_buffer=true<CR>', { desc = 'file browser' })

