mkdir -p "$XDG_CONFIG_HOME/borders"
mkdir -p "$XDG_CONFIG_HOME/git"
mkdir -p "$XDG_CONFIG_HOME/kitty"
mkdir -p "$XDG_CONFIG_HOME/nvim/spell"
mkdir -p "$XDG_CONFIG_HOME/lua"
mkdir -p "$XDG_CONFIG_HOME/pip"
mkdir -p "$XDG_CONFIG_HOME/skhd"
mkdir -p "$XDG_CONFIG_HOME/starship"
mkdir -p "$XDG_CONFIG_HOME/tmux"
mkdir -p "$XDG_CONFIG_HOME/yabai"
mkdir -p "$XDG_CONFIG_HOME/zsh"

mkdir -p "$XDG_DATA_HOME/redis"
